/* config.h.  Generated by cmake from config.h.cmake  */

#define KCLIENT_VERSION "${PROJECT_VERSION}"
#cmakedefine KCLIENT_PLUGIN_PATH "${KCLIENT_PLUGIN_PATH}"
#cmakedefine KCLIENT_GIT_REVISION "${KCLIENT_GIT_REVISION}"

/* Enable portable build */
#cmakedefine PORTABLE_BUILD

/* Disable DBus support */
#cmakedefine DISABLE_DBUS

#cmakedefine01 HAVE_LIBINTL
